name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  terraform-test:
    name: 'Terraform Test'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Validate
      run: terraform validate

  # terraform-test:
  #   name: 'Terraform Run'
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Terraform Plan
  #     run: terraform plan

  #   - name: Terraform Apply
  #     run: terraform apply